CREATE TABLE "Admin" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Admin_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");

CREATE TABLE "SiteSettings" ("id" TEXT NOT NULL DEFAULT 'main', "logoText" TEXT NOT NULL DEFAULT 'MS', "greeting" TEXT NOT NULL, "name" TEXT NOT NULL, "headline" TEXT NOT NULL, "location" TEXT NOT NULL, "heroDescription" TEXT NOT NULL, "aboutTitle" TEXT NOT NULL DEFAULT 'About Me', "aboutParagraphs" TEXT[], "contactTitle" TEXT NOT NULL, "contactText" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT NOT NULL, "profileImageUrl" TEXT, "resumeUrl" TEXT, "footerText" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocialLink" ("id" TEXT NOT NULL, "label" TEXT NOT NULL, "url" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT 'link', "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "SocialLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SkillCategory" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT 'code', "skills" TEXT[], "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "SkillCategory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Experience" ("id" TEXT NOT NULL, "company" TEXT NOT NULL, "title" TEXT NOT NULL, "period" TEXT NOT NULL, "location" TEXT NOT NULL, "points" TEXT[], "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "Experience_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectCategory" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "ProjectCategory_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ProjectCategory_slug_key" ON "ProjectCategory"("slug");
CREATE TABLE "Project" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "imageUrl" TEXT, "technologies" TEXT[], "githubUrl" TEXT, "liveUrl" TEXT, "featured" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, "categoryId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Certification" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "issuer" TEXT NOT NULL, "period" TEXT NOT NULL, "description" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "Certification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Education" ("id" TEXT NOT NULL, "degree" TEXT NOT NULL, "institution" TEXT NOT NULL, "period" TEXT NOT NULL, "highlight" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "Education_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Project" ADD CONSTRAINT "Project_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ProjectCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
